name: discourse
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  # app architecture
  get: ^4.6.1

  # firebase for backend
  firebase_core: ^1.10.5
  firebase_auth: ^3.3.3
  firebase_storage: ^10.2.3
  cloud_firestore: ^3.1.4

  # for interfacing with other apis
  http: ^0.13.4

  # miscellaneous
  image_picker: ^0.8.4+4
  cached_network_image: ^3.2.0
  path_provider: ^2.0.1
  flutter_image_compress: ^1.0.0
  photo_view: ^0.13.0
  fluentui_system_icons: ^1.1.153
  scrollable_positioned_list: ^0.2.3

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Avenir
      fonts:
        - asset: assets/fonts/AvenirLTStd-Roman.otf
        - asset: assets/fonts/AvenirLTStd-Medium.otf
          weight: 500
        - asset: assets/fonts/AvenirLTStd-MediumOblique.otf
          weight: 500
          style: italic
        - asset: assets/fonts/AvenirLTStd-Heavy.otf
          weight: 700
